feat: add paralax section
KseniyaSokolovskaya/hiqo-sokolovskaya-markup pull request #3
Opened 2019-06-14 09:47 UTC by KseniyaSokolovskaya

add paralax section with perfect pixel

2019-06-14 10:01 UTC, angelinabylitskaya requested changes
Please, fix code in accordance with comments. All issues can be found several times.

2019-06-14 10:01 UTC, angelinabylitskaya commented on scss/components/_common.scss
> +    font-family: 'Raleway',sans-serif;
Mode fonts to a variable. Consider creating a mixin for fonts definitions.

2019-06-14 10:01 UTC, angelinabylitskaya commented on scss/components/_common.scss
> +.title{
Missed space before `{`

2019-06-14 10:01 UTC, angelinabylitskaya commented on scss/components/_common.scss
> +    color: #fafafa;
Move colors to variables.

2019-06-14 10:01 UTC, angelinabylitskaya commented on scss/components/_common.scss
> +    font-family: 'Myriad Pro';
Move font to a variable. Add alternative font.

2019-06-14 10:01 UTC, angelinabylitskaya commented on scss/components/_common.scss
> +      content: "“";
Better to use background image or symbol.

2019-06-14 10:06 UTC, angelinabylitskaya commented
![image](https://user-images.githubusercontent.com/19670773/59501880-28658280-8ea5-11e9-815d-c31c3e92f0be.png)
Design mismatch.

2019-06-17 07:53 UTC, kobweb commented on scss/components/_common.scss
> +    width: 151px;
Don't use fixed width, use padding and min-width instead.

2019-06-17 07:53 UTC, kobweb commented on scss/components/_common.scss
> +    margin-right: 17px;
Use some kind of modificator for indents, in perspective not all your buttons will have an indent.

2019-06-17 08:30 UTC, kobweb approved these changes

2019-06-17 08:35 UTC, merged